export const ICONS = {
  download: 'mdi:download',
  gmail: 'skill-icons:gmail-light',
  spain: 'circle-flags:lang-es',
  england: 'circle-flags:en',
  search: 'mdi:magnify',
  person: 'mdi:account',
  rightArrow: 'solar:alt-arrow-right-line-duotone',
  leftArrow: 'solar:alt-arrow-left-line-duotone',
  topArrow: 'streamline:interface-arrows-button-up-arrow-up-keyboard',
  bottomArrow: 'streamline:interface-arrows-button-down-arrow-down-keyboard',
  instagram: 'cib:instagram',
  tiktok: 'cib:tiktok',
  upload: 'line-md:uploading-loop',
  close: 'iconamoon:close',
  calendar:
    'streamline:interface-calendar-date-month-thirty-thirty-calendar-date-week-day-month',
  contact: 'streamline:contact-phonebook-2',
  quote: 'material-symbols:request-quote-outline',
  question: 'material-symbols:question-mark',
  legal: 'hugeicons:legal-01',
  web: 'mdi:web',
  cookies: 'proicons:cookies',
  privacy: 'iconoir:privacy-policy',
  rotate: 'mdi:rotate-3d-variant',
}
